global:
    sendAnonymousUsage: false

api:
    dashboard: true
    insecure: true

providers:
    docker:
        endpoint: unix:///var/run/docker.sock

    file:
        filename: /etc/traefik/dynamic_conf.yaml
        watch: true

log:
    level: DEBUG
    format: common
    filePath: /var/log/traefik.log

entryPoints:
    web:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https

    websecure:
        address: ':443'
